### ISSUE TITLE
fix(web-platform): bot-fixture.ts uses Bun-specific import.meta.path, breaks Docker build

### ISSUE THREAD

**Issue by deruelle** [jikig-ai/soleur#3055]
## Summary

Web Platform Release workflow has been failing on every commit since PR #3045 merged (commit `1edf7a62`). The build fails during `next build` typecheck because `plugins/soleur/skills/ux-audit/scripts/bot-fixture.ts:263` uses Bun-specific `import.meta.path`, which is not part of the standard `ImportMeta` interface that TypeScript's strict mode (and `next build`) enforces.

## Cause

PR #3045 (`fix(web-platform): populate /mnt/data/plugins/soleur via image-baked`) bakes `plugins/soleur/` into the web-platform Docker image. Once vendored, `bot-fixture.ts` becomes part of the typechecked surface even though it's a Bun-only utility script.

## Error

```
./_plugin-vendored/skills/ux-audit/scripts/bot-fixture.ts:263:45
Type error: Property 'path' does not exist on type 'ImportMeta'.

> 263 |     console.error(`Usage: bun ${import.meta.path} <seed|reset>`);
```

## Failing runs

- `692f7277` (PR #3054 merge) — failure 25122642826
- `1edf7a62` (PR #3045 merge, first failure) — failure 25121733747
- `87bc9227` and earlier — success

## Fix options

1. Replace `import.meta.path` with cross-runtime equivalent (`fileURLToPath(import.meta.url)` or hardcode `bot-fixture.ts` in the usage string).
2. Exclude `plugins/soleur/skills/ux-audit/scripts/**` from the web-platform tsconfig include (these are plugin-runner scripts, not webapp code).

Option 1 is the smaller, more targeted fix.

## Impact

Every merge to main since 2026-04-29 has failed the Web Platform Release. Prod is running stale (last successful build: `87bc92273e` — pre-#3045). This is a silent production-deploy outage per workflow gate `wg-after-a-pr-merges-to-main-verify-all`.

## Triaged in

PR #3054 (security-alerts one-shot) — discovered while verifying all release workflows succeeded post-merge. Pre-existing regression, not introduced by #3054.
