### ISSUE TITLE
release: web-platform deploy has not run since 2026-08-07 — image build fails on claude-agent-sdk ESM import (6 consecutive)

### ISSUE THREAD

**Issue by deruelle** [jikig-ai/soleur#7395]
**The web-platform production deploy has not run since 2026-08-07.** Every merge to `main` since then has built an image that fails, so `deploy` is skipped and production continues serving the pre-08-07 commit.

Found during post-merge verification of PR #7372. **Not caused by that PR** — it is the sixth consecutive failure.

## Evidence

`web-platform-release.yml` on `main`, most recent first:

| Commit | Conclusion | When |
|---|---|---|
| `b3754369` | failure | 08-10 09:25 |
| `5b75b43d` | failure | 08-10 08:06 |
| `f9deb2d8` | failure | 08-09 20:06 |
| `76d09947` | failure | 08-09 18:05 |
| `1839306b` | failure | 08-07 17:03 |
| `e9a44b05` | failure | 08-07 16:35 |

Job breakdown on `b3754369` (run `31374522264`):

```
success  await-ci
failure  release / release        <- image build
success  verify-doppler-secrets
skipped  migrate
skipped  verify-migrations
skipped  deploy                   <- consequence
skipped  live-verify
```

`deploy` is gated on the build, so a failed build silently means "production unchanged". Nothing about that reads as an outage in the run list — the release job is the only red, and it is not a required PR check.

## Cause

Next.js build failure inside the Docker image build:

```
Module not found: ESM packages (@anthropic-ai/claude-agent-sdk) need to be imported.
Use 'import' to reference the package instead.

Import trace for requested module:
  ./server/sandbox-startup-classifier.ts
```

A second trace in the same build points at `./server/inngest/functions/cron-ux-audit.ts` → `./app/api/inngest/route.ts` with *"Critical dependency: the request of a dependency is an expression"*, which may be the same root or a separate symptom.

`@anthropic-ai/claude-agent-sdk` is ESM-only. `apps/web-platform/server/sandbox-startup-classifier.ts` reaches it through a path Next.js resolves as CJS. Verified present on `5b75b43d` and `f9deb2d8` as well (2 log hits each), so the cause is stable across all sampled failures rather than a flake.

## Why it went unnoticed for three days

Worth recording, because the detection gap is reusable:

- **The release job is not a required PR check.** PR CI is green, auto-merge fires, the release fails afterward. Nothing blocks and nothing pages.
- **`gh run list --branch main --commit <sha>` did not return this workflow** during post-merge verification, so an automated "any failures on the merge commit?" check reported **failures: 0** while this run was red. It surfaces via `gh run list --workflow web-platform-release.yml`. Any verification keyed on the commit filter alone inherits this blind spot.
- **A skipped job reads as benign.** `deploy: skipped` looks like a path filter declining to run, not like a build that died upstream.

## Scope

- Production is running the last successfully-built image (pre-08-07). Runtime behaviour is stale but *stable* — this is a deploy-freeze, not a crash.
- Anything merged since 08-07 that changes runtime behaviour is **not live**, whatever its PR body claims.
- Docs/legal changes are unaffected — they publish through `deploy-docs.yml`, which is green (verified live: `soleur.ai/legal/*` serves current content).

## Fix

- [ ] Make the ESM import work in the Next.js build — the usual shapes are a dynamic `await import()` at the call site, adding the package to `serverExternalPackages` in `next.config.ts`, or moving the classifier behind a boundary the client graph never reaches
- [ ] Confirm whether the `cron-ux-audit.ts` → `route.ts` "critical dependency" trace is the same root or separate
- [ ] Re-run the release on `main` and confirm `deploy` executes rather than skips
- [ ] Verify the deployed image digest actually changes — a green run is not proof the new bytes are serving
- [ ] Decide whether `release / release` should page. Six silent failures over three days is the argument that it should

## Detection follow-up

Post-merge release verification should not rely on `--commit` filtering alone. Enumerate by workflow name, or assert that the expected workflow set is *present* rather than merely non-failing — the same "absence is not success" shape already recorded elsewhere in this repo.

**Comment by deruelle** [comment]
## Live evidence, and the window may be wider than six runs

Measured just now against production:

```
GET https://app.soleur.ai/health  -> 200
{"status":"ok","version":"0.249.4","build_sha":"f838839ef11119ac46f4d38ccf926472dee393a8",
 "supabase":"connected","sentry":"configured","uptime":512552,"memory":394}
```

**`uptime` 512552s ≈ 5.93 days**, so the serving process started around **2026-08-04** — earlier than the oldest failure sampled in the issue body (08-07 16:35). Either the freeze predates that run, or the sampled window simply did not reach far enough back. Worth walking the release history further before assuming six is the total.

`build_sha` is `f838839e`, not the current `main` HEAD `b3754369`.

**The tag advanced while the deploy did not.** `v3.247.2` was created today — `Version Bump and Release` succeeded on the same commit where `release / release` failed. So the release *tag* moves on every merge while the *image* does not, which is a large part of why this reads as healthy from the outside: there is a fresh tag, a green PR, and a 200 on `/health`.

**Not an outage.** The service is up and stable on the last good image. The risk is silent staleness: anything merged since the freeze is not live regardless of what its PR body says.

Adds one item to the fix list:

- [ ] Walk `web-platform-release.yml` history back past 2026-08-07 to find the true first failure, and reconcile that date against the ~08-04 process start
- [ ] Consider asserting `build_sha == <merge commit>` in post-merge verification. A 200 on `/health` and a fresh release tag are both satisfiable while the deployed bytes are days old; the SHA comparison is the check that cannot be satisfied by a stale image

**Comment by deruelle** [comment]
### The outage persists but the failing stage has MOVED — the ESM build failure in the title is no longer what fails

Found during post-merge verification of PR #7371 (run [31383149164](https://github.com/jikig-ai/soleur/actions/runs/31383149164), commit `f13f206a1`). **Not caused by that PR** — its diff has zero overlap with the release/docker/zot surface (the only path matching `registry` is `function-registry-count.test.ts`, matched on the word in a filename).

Flagging because closing this issue on "the claude-agent-sdk ESM import is fixed" would be wrong: the image now builds and pushes fine, and production is still not deploying.

**Step outcomes in the `release` job — the build stages all pass:**

| Step | Result |
|---|---|
| Build and push Docker image | **success** |
| Set docker_pushed output | success |
| Sign image (cosign keyless) | success |
| Bridge to zot registry (CF Tunnel) | success |
| Mirror image GHCR→zot (crane) + cosign-sign the zot digest | **failure** |

**The new failure mode** — zot resets the connection and 500s mid-upload, so the blob lands corrupt and the digest check rejects it:

```
retrying Head  http://127.0.0.1:5000/v2/…/blobs/sha256:1cb89e…: EOF
retrying Patch http://127.0.0.1:5000/v2/…/blobs/uploads/…: read: connection reset by peer
retrying PATCH http://127.0.0.1:5000/v2/…/blobs/uploads/…: unexpected status code 500 Internal Server Error
Error: PUT …/blobs/uploads/…: DIGEST_INVALID: provided digest did not match uploaded content
```

`DIGEST_INVALID` here is a *symptom*, not a client bug: crane uploaded correct bytes, the server dropped some of them. That is the signature of a registry that cannot write — which is exactly #7341 (`/var/lib/zot` 100% full, zot restarting ~4x/min). #7295 is also relevant: the ghcr-fallback emitter being structurally dark is why `zot_mirror_f…` did not surface this earlier.

**Streak.** The 12 most recent `Web Platform Release` runs on `main` are all `failure` (oldest in that window `54451536b`, 08-06 12:03) — I did not check further back, so treat 08-06 as the edge of the measured window, not a proven start date.

**Consequence.** The release is explicitly `BLOCKED and will not deploy`, so production still serves the pre-08-07 commit. A plain re-run will not clear it while the host cannot accept writes — the backfill the error suggests (`crane copy` + `cosign sign`, and the message is right that a bare `crane copy` is insufficient because it does not write the signature the host verifies) needs registry-host access, which is blocked on #7341.

**Comment by deruelle** [comment]
**The stated cause no longer matches what the runs are failing on.** Measured just now across the last six `Web Platform Release` runs on `main`:

| run | head | `Build and push Docker image` | first failing step |
|---|---|---|---|
| 31420397392 | `bf73bd401` | **success** | Mirror image GHCR→zot (crane) + cosign-sign the zot digest |
| 31396142213 | `bab29e651` | **success** | Mirror image GHCR→zot |
| 31391358858 | `1cbb857c0` | **success** | Mirror image GHCR→zot |
| 31383149164 | `f13f206a1` | **success** | Mirror image GHCR→zot |
| 31381140172 | `96670783f` | **success** | Mirror image GHCR→zot |
| 31379319736 | `9a9932b9e` | **success** | Mirror image GHCR→zot |

The image builds, pushes to GHCR, and cosign-signs successfully in all six. The blocker is the **zot mirror**, which then skips `Finalise release (publish draft)`.

This title attributes the blockage to "image build fails on claude-agent-sdk ESM import". That may have been accurate when filed, but it is not what these six runs fail on — so anyone picking this up from the title would go looking at the build, which is green.

Likely the same root as the zot cluster already open: #7247 (zot crash-looping on the registry host), #7267 (zot unreachable from both web hosts), #7378 (`crane validate` false-positives on buildx attestation manifests). #7378 in particular names `crane`, which is the tool this step uses.

Count update: this is now **8 consecutive** (the 6 above plus the two earlier today), and `bf73bd401` is PR #7407's merge.

Raised from a `/ship` post-merge verification — not filing a new issue, since this one already covers the outage; only correcting its premise so the fix is aimed at the right step.

**Comment by deruelle** [comment]
**Impact quantified from `/health`, since the thread has the outage but not its size:**

```
production build_sha : f838839ef  (2026-08-04 11:09 UTC)  version 0.249.4
main HEAD            : bf73bd401  (2026-08-10 18:42 UTC)
commits unshipped    : 36
```

So production is **36 commits / 6 days stale**, not the ~3 days the title's "since 2026-08-07" implies — the last *successful* deploy may have run on 08-07, but the artifact it left live is from 08-04.

Everything else is green, which is what makes this quiet: `/health` returns 200, `status: ok`, `supabase: connected`, `sentry: configured`, and all Sentry cron monitors report healthy. Nothing pages, because the running container is fine — it is just old. `Version Bump and Release` also keeps succeeding and tagging (v3.248.1 for this merge), so the release *tags* advance while the deployed artifact does not — a tag is not evidence of a deploy.

**Comment by deruelle** [comment]
## The build is not what is failing — measured across the last 4 merges

This issue's title names the `@anthropic-ai/claude-agent-sdk` ESM import as the cause. That is not what the job reports. Checked the per-step conclusions via `gh api repos/jikig-ai/soleur/actions/jobs/<id>` for the four most recent `Web Platform Release` runs on `main`:

| Run | `Build and push Docker image` (step 21) | Failing step |
|---|---|---|
| 31422599432 (#7398) | **success** | 26 — `Mirror image GHCR→zot (crane) + cosign-sign the zot digest` |
| 31420397392 (#7407) | **success** | 26 — same |
| 31396142213 (#7388) | **success** | 26 — same |
| 31383149164 | **success** | 26 — same |

The ESM line does appear in the build log:

```
#22 118.2 Module not found: ESM packages (@anthropic-ai/claude-agent-sdk) need to be
imported. Use 'import' to reference the package instead.
```

but it is **non-fatal** — step 21 concludes `success` in all four runs, and the image is built, pushed to GHCR, and cosign-signed (steps 21–24 all green). A grep of the log finds that string and stops there; the step conclusions say the build finished.

## What actually blocks the deploy

Step 26 fails at stage `copy_v` after all 3 retries:

```
##[error]zot mirror FAILED at stage 'copy_v' for 127.0.0.1:5000/jikig-ai/soleur-*** (rc=1)
— zot did not receive the 'v0.249.5' tag of this image, so the host has nothing to pull
and GHCR is not a fallback. This release is BLOCKED and will not deploy.
```

`deploy`, `migrate` and `verify-migrations` are then all `skipped`, which is why prod is stale. The step's own error text is careful to say it reports what it MEASURED — the copy into zot did not land.

## Likely upstream

**#7341** (`/var/lib/zot is 100% full on the registry host`) is the obvious candidate for a `copy_v` write failure, and #7272 / #7267 / #7270 describe the same host flapping. I have **not** verified that link — I am reporting the stage that fails, not asserting the cause, which is the mistake this comment is correcting. Someone with registry-host access should confirm whether the disk is still full before closing anything.

## Why it matters that the title is wrong

The title sends the next person to the Next.js/ESM surface, which is green. Retitling toward the zot mirror (and linking #7341) points at the thing that is actually red. Filed from PR #7398's post-merge verification; that PR is docs+bash only and touches zero `apps/web-platform/` files, so it neither caused nor is affected by this.

**Comment by deruelle** [comment]
**Still broken, but the root cause has CHANGED.** The `claude-agent-sdk` ESM import named in the title is no longer what fails. Measured 2026-08-26 while shipping PR #7653.

## Current failure

```
Type error: Cannot find module './test/repo-wide-suites' or its corresponding type declarations.
ERROR: failed to build: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1
```

## Mechanism

1. `apps/web-platform/vitest.config.ts:4` — `import { REPO_WIDE_SUITES } from "./test/repo-wide-suites";`
2. `apps/web-platform/.dockerignore:106` — `test/`
3. `vitest.config.ts` IS in the Docker build context; its import target is NOT.
4. `npm run build` typechecks `vitest.config.ts`, cannot resolve the module, and the image build fails.

The import was added by #7666 (`8eb877477`, "split the repo-wide parity guards out of `unit`"). That PR is correct in-repo — the file exists and every local suite passes; it is only unbuildable inside the pruned Docker context.

## Regression window — exact

| run | commit | result |
| --- | --- | --- |
| 2026-08-20 20:35 | `dc201e757` | **success (last one)** |
| 2026-08-20 21:16 | `8eb877477` (#7666) | failure — first |
| 2026-08-20 21:51 | `ff8ac47f7` | failure |
| 2026-08-25 11:56 | `f2f3cc4bc` | failure |
| 2026-08-25 12:40 | `42df7d416` | failure |
| 2026-08-25 13:18 | `dd8683701` | failure |
| 2026-08-25 13:53 | `c33e7d88a` | failure |
| 2026-08-25 14:31 | `924994b2f` (#7653) | failure |

Seven consecutive. Corroborated independently: `https://app.soleur.ai/health` still reports
`build_sha: dc201e757f63faa2001b4cf3e4ae4d8e6748bb38` — exactly the last successful build. **Production has not received a deploy since 2026-08-20.**

## Not caused by #7653

PR #7653 touches `apps/web-platform/infra/git-data-runcmd-rehearsal.test.sh`, which matches the release path filter, so it TRIGGERED a release run — but the failure predates it by six runs and five days. Its own release job failed at the same typecheck. Recording this explicitly so the newest red run is not mistaken for the cause.

## Candidate fixes

- Un-ignore just the imported module (`!test/repo-wide-suites.ts` in `.dockerignore`), or
- move `REPO_WIDE_SUITES` out of `test/` into a path already in the build context, or
- exclude `vitest.config.ts` from the production typecheck.

The first is smallest; the second is probably the right shape, since a build-context file importing from an ignored directory will keep re-breaking.

## Worth noting

Seven consecutive failed production deploys did not surface anywhere an operator would see. That is the same defect class #7653 just closed elsewhere in CI — a gate whose failure is indistinguishable from silence — and it argues for an alarm on consecutive release failures rather than per-run redness.

**Comment by deruelle** [comment]
## Record correction — measured 2026-08-26/27

This issue was filed 2026-08-10 against a **different failure** than the one that was live. Every row below was measured this session.

| This issue claims | Measured reality |
|---|---|
| Root cause is `Module not found: ESM packages (@anthropic-ai/claude-agent-sdk)` from `server/sandbox-startup-classifier.ts` | A **warning**, not the breaker. It appears under `⚠ Compiled with warnings` in the last GREEN run (`32414879638` / `dc201e75`) that deployed to production successfully — and again in this session's own `docker build --target builder`, which exited **0** and produced an image. A line present in two successful builds is not what fails the third. |
| Fix by adding the package to `serverExternalPackages` | `next.config.ts` has listed it there since the MVP commit `5b8e24206`. The proposed fix was already in the tree. |
| Second trace: `cron-ux-audit.ts` → `app/api/inngest/route.ts` "Critical dependency" | **Separate and non-blocking.** 3 occurrences in that same GREEN run. A dynamic-`require` warning. |
| Deploy has not run since **2026-08-07**; 19 days stale | **Six days.** Eleven consecutive runs succeeded on 08-20; last fully green run `32414879638` / `dc201e75` / 2026-08-20T20:35Z. Corroborated independently: `https://app.soleur.ai/health` reports `build_sha=dc201e757f63faa2001b4cf3e4ae4d8e6748bb38`. |
| Six consecutive failures, all one cause | **Three unrelated causes conflated.** `31374522264` (`b3754369`, 08-10 — the run this issue cites) built the image *successfully* and died at the zot mirror (`DIGEST_INVALID` → `500` → `zot mirror FAILED at stage 'copy_v'`). `32293304541` (08-19) failed at `verify-migrations`. The current class began at `32418522892` (`8eb87747`, 08-20T21:16Z). |
| `release / release` fails silently; decide whether it should page | **Not silent — it paged three times over.** `release-outcome` emailed on every failure (run `32860030881`: `Release-failure email sent to ops@jikigai.com (HTTP 200)`); `scheduled-prod-version-drift.yml` returned `DRIFT_SUSTAINED` every ~30–60 min; it filed **#7676** (`p0-critical` + `action-required`), open since 08-21. The gap was **response**, not detection. |
| Post-merge verification must not rely on `--commit` filtering alone | **Confirmed, with a sharper cause** — split into its own issue. `gh run list --commit <sha> -L 200` returns *exactly* 200 rows (saturates the cap) with `web-platform-release` absent from that page. |

### The actual cause

```
Failed to compile.
Type error: Cannot find module './test/repo-wide-suites' or its corresponding type declarations.
> 4 | import { REPO_WIDE_SUITES } from "./test/repo-wide-suites";
```

`vitest.config.ts` is in the Docker build context and is type-checked by `next build`. `test/` is excluded by `.dockerignore` line 106. The import crosses that boundary, so the in-container type-check cannot resolve it. Introduced 2026-08-20.

Reproduced independently of CI with a busybox context probe: `vitest.config.ts` PRESENT, `test/repo-wide-suites.ts` ABSENT.

This is the **fifth occurrence** of the class, and `.dockerignore` already documents an earlier one in its own comments ("the 1edf7a62 release failed for exactly this reason").

### Scope changes

Three of the six checklist items are cut as non-causal or already-bought (the ESM import, the critical-dependency trace, the alerting item). The guard widening and the detection follow-up are split into their own issues so the P0 unfreeze is hostage to neither.

---

## Resolution

Fixed by #7714 (`bc0fb281b`), which re-included `!test/repo-wide-suites.ts` in `.dockerignore` and added `apps/web-platform/test/docker-context-import-containment.test.ts` — a guard that parses `.dockerignore` at runtime (including `!` negations) and fails when a build-context file imports an excluded one. Production unfroze on 2026-08-27 and is serving `b5ef7b91` (`/health` confirms).

PR #7704 approached the same defect by moving the file out of `test/` instead. It is closed as superseded — the freeze is over, and #7714's guard supplies the self-enforcing tripwire that was the main argument for the move.

Two findings from #7704's review that outlive it:

- **The class is not fully closed.** `lib/feature-flags/identity.test.ts:9` imports `@/test/helpers/mock-supabase` while sitting in the build context, and `app/internal/github-app-init/page.tsx:3` imports `@/infra/github-app-manifest.json`, which is safe *only* because of a single `.dockerignore` re-include line. The first is masked by a Next.js internal that discards diagnostics from `*.test.*` files (`runTypeCheck.js`), so it has been erroring silently inside every image build for months — a vendor implementation detail, not a guarantee.
- **A live production exposure, filed as #7749.** The deploy that ended this freeze also carried the code half of #7640, disarming the GitHub Pages cert-expiry poll while its Sentry monitor was already disabled and the Cloudflare Pages cutover that would justify both has not landed.

**Comment by deruelle** [comment]
Fixed by #7714 (`bc0fb281b`). Production unfroze 2026-08-27 and is serving `b5ef7b91`; `web-platform-release.yml` has been green on `main` since.

The record correction above stands: this issue's stated root cause (the `@anthropic-ai/claude-agent-sdk` ESM line) was a warning present in builds that succeeded, and the freeze was 6 days from 08-20, not 19 from 08-07. Follow-up exposure filed as #7749.
