### ISSUE TITLE
fix(ci): Tenant integration (dev-Supabase) red on main since f38b18ca — cron-bash-allowlist-hook module resolution

### ISSUE THREAD

**Issue by deruelle** [jikig-ai/soleur#5360]
## Problem
The **Tenant integration (dev-Supabase)** workflow has been RED on `main` since commit `f38b18ca` (~2026-06-15 14:14 UTC). It was green at `690d1c22` (13:16) and has failed on every subsequent main commit (`f38b18ca`, `f6b94170`, `71758cc2`, `4209e11f`, …).

Failing assertion (live-dev shard, `Run tenant-isolation tests`):
```
Error: Cannot find module '/tmp/soleur-no-such-spawn-cwd-xyz/apps/web-platform/server/inngest/cron-bash-allowlist-hook.mjs'
```
A `cron-bash-allowlist-hook` test resolves a module path relative to a deliberately-nonexistent spawn cwd; the resolution now throws (uncaught) instead of being handled, crashing the shard. Example run: https://github.com/jikig-ai/soleur/actions/runs/27557389226

## Provenance
- First-failing commit: `f38b18ca` (bisect the 690d1c22 → f38b18ca window). NOT introduced by PR #5350 (in-flight work durability — different subsystem) nor #5326 (outbound-email); both merged after the failure began.
- Subsystem: `apps/web-platform/server/inngest/cron-bash-allowlist-hook` + its tenant-integration test harness.

## Why filed (not fixed inline)
Discovered during PR #5350's post-merge release verification (`wg-after-a-pr-merges-to-main-verify-all`). It is a pre-existing main-red failure in a subsystem unrelated to that PR — scope discipline keeps it a separate issue/PR. Tenant integration is not a required merge check, so it does not block merges, but a persistently-red main check normalizes breakage.

## Suggested fix
Bisect `690d1c22..f38b18ca`; the test likely needs to catch the `Cannot find module` rejection (or the harness changed how it resolves the `.mjs` path under a missing spawn cwd).

**Comment by deruelle** [comment]
Resolved on main — **Tenant integration (dev-Supabase)** is durably green.

**Evidence:** last 4 consecutive runs green, including HEAD `c93d937` (run [27575582551](https://github.com/jikig-ai/soleur/actions/runs/27575582551), `tenant-integration` job = success). The red streak ended at `7d5dc62`; last failure was `e99cbdc`.

**Fixes** (both landed after this issue was filed):
- #5375 `882f86d` — `fix(workspace): unconditionally ensure workspace dir before sandbox construction` — addresses the root cause: a missing spawn cwd causing `Cannot find module '…/cron-bash-allowlist-hook.mjs'`. (Earlier partial attempt #5367 still failed; #5375 is the one that stuck.)
- #5376 `c2a2416` — `fix(tenant-integration): revert dev routine_runs drift + per-ref WORM-cascade gate + denied_jti Art-17 cascade` — cleared remaining tenant-integration drift.

The test file `cron-bash-allowlist-hook.test.ts` was unchanged, consistent with the harness/spawn-cwd diagnosis rather than the assertion.
